export {
  CREATE_UID_FUNCTION_SQL,
  CREATE_PAGES_TABLE_SQL,
  CREATE_POSTS_TABLE_SQL,
  CREATE_SETTINGS_TABLE_SQL,
  CREATE_CONTACTS_TABLE_SQL,
  CREATE_TEMPLATES_TABLE_SQL,
  CREATE_COMMENTS_TABLE_SQL,
  CMS_SCHEMA_SQL_SAFE,
  CMS_MIGRATIONS_SQL,
} from "./schema-sql.mjs"

export type CmsTable = "pages" | "posts" | "settings" | "contacts" | "templates"
