/**
 * Reports whether MCP authoring env vars are present.
 * Does not print secret values unless --write-file <path> is passed.
 */
import fs from "node:fs"
import { loadEnvFile, env } from "./lib/env.mjs"

loadEnvFile()

const KEYS = [
  "ORBITYPE_SQL_API_KEY",
  "ORBITYPE_S3_PUBLIC_API_KEY",
  "ORBITYPE_S3_PRIVATE_API_KEY",
]

const writeIdx = process.argv.indexOf("--write-file")
const writeFile = writeIdx >= 0 ? process.argv[writeIdx + 1] : undefined

function resolveValue(key) {
  const direct = env(key)
  if (direct) return direct
  if (key === "ORBITYPE_SQL_API_KEY") return env("ORBITYPE_API_SQL_KEY")
  return ""
}

if (writeFile) {
  const lines = [
    "# Generated by pnpm run mcp:env -- --write-file",
    "# Restrictive permissions applied. Do not commit this file.",
    "",
  ]
  for (const key of KEYS) {
    const value = resolveValue(key)
    if (value) {
      lines.push(`export ${key}="${value}"`)
    } else {
      lines.push(`# export ${key}="..."`)
    }
  }
  fs.writeFileSync(writeFile, lines.join("\n") + "\n", { mode: 0o600 })
  console.log(`Wrote exports to ${writeFile} (mode 0600).`)
  console.warn(
    "Warning: this file contains secrets. Do not commit or paste it.",
  )
  process.exit(0)
}

console.log("# MCP env status (values hidden).")
console.log(
  "# To write shell exports: pnpm run mcp:env -- --write-file /tmp/mcp-env.sh\n",
)

for (const key of KEYS) {
  const value = resolveValue(key)
  console.log(`${key}: ${value ? "present" : "missing"}`)
}
